### ISSUE TITLE
Need to update AndroidPluginTemplate with Gradle Version 3.1.4 

### ISSUE THREAD

**Issue by dondutunel** [smartface/sf-plugin-firebase#5]
According to this guide <https://developer.smartface.io/docs/android-plugins#section-plugin-development-prerequisites> AndroidPluginTemplate is required but this snippet is sync with old gradle version. Can you please update this zip file?

**Comment by furkanarabaci** [comment]
The firebase structure has been refactored. Now there is no need to sync it again. Closing the issue.
