### ISSUE TITLE
Read me improvement request 

### ISSUE THREAD

**Issue by dondutunel** [smartface/sf-plugin-firebase#6]
Please improve following steps to make usage clear 
- [There](https://github.com/smartface/sf-plugin-firebase#android) is an explanation on Step 2 like 'This repository already contains ready plugin project.' But its not clear where the plug and play project placed.  

- 'Just left to you open in Android Studio (preferred version 3.2 ) and placed google-services.json file into plugin project's app folder.' Indeed that is clear to understand but it might be confused for apart from mobile developers. It could be nice if a path or something explicative is added.

**Comment by furkanarabaci** [comment]
Seems like those are fixed. Closing the issue.
